# Generated by Django 2.1.7 on 2019-06-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('comment', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
